 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyKyTucXa;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Huynh Hau
 */
public class QuanLyPhong extends javax.swing.JFrame {

    DefaultTableModel defaultTableModel = new DefaultTableModel();
    ThongTinPhong h40 = new ThongTinPhong();

    public QuanLyPhong() {
        initComponents();

        TableBangThongTin.setModel(defaultTableModel);

        defaultTableModel.addColumn("Tên phòng");
        defaultTableModel.addColumn("Mã phòng");
        defaultTableModel.addColumn("Loại phòng");
        defaultTableModel.addColumn("Số sinh viên hiện tại");
        defaultTableModel.addColumn("Số sinh viên tối đa");
        defaultTableModel.addColumn("Tình trạng phòng");
        
    }

    /**
     * Creates new form QuanLyPhong
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelSoSinhVienToiDa = new javax.swing.JLabel();
        TextFieldSoSinhVienHienTai = new javax.swing.JTextField();
        ButtonThem = new javax.swing.JButton();
        TextFieldTinhTrangPhong = new javax.swing.JTextField();
        ButtonSua = new javax.swing.JButton();
        TextFieldSoSinhVienToiDa = new javax.swing.JTextField();
        ButtonXoa = new javax.swing.JButton();
        ButtonThoat = new javax.swing.JButton();
        TextFieldTenPhong = new javax.swing.JTextField();
        TextFieldMaPhong = new javax.swing.JTextField();
        LabelPhongCanTim = new javax.swing.JLabel();
        TextFieldPhongCanTim = new javax.swing.JTextField();
        ButtonTimKiem = new javax.swing.JButton();
        LabelTenPhong = new javax.swing.JLabel();
        LabelMaPhong = new javax.swing.JLabel();
        LabelLoaiPhong = new javax.swing.JLabel();
        LabelSoSinhVienHienTai = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableBangThongTin = new javax.swing.JTable();
        LabelTinhTrangPhong = new javax.swing.JLabel();
        ComboBoxGioiTinh = new javax.swing.JComboBox<>();
        LabelThongTin1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết của phòng:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setToolTipText("");

        LabelSoSinhVienToiDa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelSoSinhVienToiDa.setText("Số Sinh Viên Tối Đa: ");

        TextFieldSoSinhVienHienTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldSoSinhVienHienTaiActionPerformed(evt);
            }
        });

        ButtonThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuanLyKyTucXa/Icons/Save-icon.png"))); // NOI18N
        ButtonThem.setText("Thêm ");
        ButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonThemActionPerformed(evt);
            }
        });

        ButtonSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuanLyKyTucXa/Icons/Actions-document-edit-icon-16.png"))); // NOI18N
        ButtonSua.setText("Sửa");
        ButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSuaActionPerformed(evt);
            }
        });

        ButtonXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuanLyKyTucXa/Icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        ButtonXoa.setText("Xóa");
        ButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonXoaActionPerformed(evt);
            }
        });

        ButtonThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuanLyKyTucXa/Icons/logout-icon-16.png"))); // NOI18N
        ButtonThoat.setText("Thoát");
        ButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonThoatActionPerformed(evt);
            }
        });

        LabelPhongCanTim.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelPhongCanTim.setText("Nhập tên phòng cần tìm: ");

        TextFieldPhongCanTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPhongCanTimActionPerformed(evt);
            }
        });

        ButtonTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonTimKiem.setIcon(new javax.swing.ImageIcon("D:\\HOCKY_221\\LT_JavaNC\\HocJavaNC\\BaiTapNhom\\src\\QuanLyKyTucXa\\Icons\\search-icon-24.png")); // NOI18N
        ButtonTimKiem.setText("Tìm Kiếm");
        ButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTimKiemActionPerformed(evt);
            }
        });

        LabelTenPhong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelTenPhong.setText("Tên Phòng:");

        LabelMaPhong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelMaPhong.setText("Mã Phòng: ");

        LabelLoaiPhong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelLoaiPhong.setText("Loại Phòng: ");

        LabelSoSinhVienHienTai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelSoSinhVienHienTai.setText("Số Sinh Viên Hiện Tại: ");

        TableBangThongTin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tên phòng", "Mã phòng", "Loại phòng ", "Số sinh viên hiện tại", "Số sinh viên tối đa", "Tình trạng phòng"
            }
        ));
        jScrollPane2.setViewportView(TableBangThongTin);

        LabelTinhTrangPhong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelTinhTrangPhong.setText("Tình Trạng Phòng: ");

        ComboBoxGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        ComboBoxGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxGioiTinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelPhongCanTim)
                    .addComponent(LabelTenPhong)
                    .addComponent(LabelMaPhong)
                    .addComponent(LabelSoSinhVienHienTai)
                    .addComponent(LabelSoSinhVienToiDa)
                    .addComponent(LabelLoaiPhong)
                    .addComponent(LabelTinhTrangPhong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextFieldTinhTrangPhong)
                    .addComponent(TextFieldSoSinhVienToiDa)
                    .addComponent(TextFieldSoSinhVienHienTai)
                    .addComponent(ComboBoxGioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TextFieldPhongCanTim, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(ButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextFieldTenPhong)
                    .addComponent(TextFieldMaPhong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPhongCanTim, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldPhongCanTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTenPhong)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(TextFieldTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelMaPhong)
                            .addComponent(TextFieldMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(LabelLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ComboBoxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelSoSinhVienHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldSoSinhVienHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelSoSinhVienToiDa)
                            .addComponent(TextFieldSoSinhVienToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTinhTrangPhong)
                            .addComponent(TextFieldTinhTrangPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        LabelThongTin1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelThongTin1.setForeground(new java.awt.Color(204, 0, 0));
        LabelThongTin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuanLyKyTucXa/Icons/home1.png"))); // NOI18N
        LabelThongTin1.setText("THÔNG TIN TỪNG PHÒNG TẠI KÝ TÚC XÁ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelThongTin1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(LabelThongTin1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxGioiTinhActionPerformed
        // TODO add your handling code here:
        //String selectedItem = (String) ComboBoxGioiTinh.getSelectedItem();
        //System.out.println("Lựa chọn loại phòng phù hợp: " + selectedItem);
    }//GEN-LAST:event_ComboBoxGioiTinhActionPerformed

    private void ButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonTimKiemActionPerformed

    private void TextFieldPhongCanTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPhongCanTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPhongCanTimActionPerformed

    private void ButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ButtonThoatActionPerformed

    private void ButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonXoaActionPerformed

    private void ButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSuaActionPerformed

    private void ButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonThemActionPerformed
        // TODO add your handling code here:
        
        h40.setTenPhong(TextFieldTenPhong.getText());
        h40.setMaPhong(TextFieldMaPhong.getText());
        //h40.setLoaiPhong(ComboBoxGioiTinh.isSelected()? 1; 0);
        h40.setSoSVHienTai(TextFieldSoSinhVienHienTai.getText());
        h40.setSoSVToiDa(TextFieldSoSinhVienToiDa.getText());
        h40.setTinhTrangPhong(TextFieldTinhTrangPhong.getText());
        TableBangThongTin.setModel(defaultTableModel);
        defaultTableModel.addRow(new Object[]{h40.getTenPhong(), h40.getMaPhong(), h40.getSoSVHienTai(), h40.getSoSVToiDa(), h40.getTinhTrangPhong()});
        
    }//GEN-LAST:event_ButtonThemActionPerformed

    private void TextFieldSoSinhVienHienTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldSoSinhVienHienTaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldSoSinhVienHienTaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QuanLyPhong().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSua;
    private javax.swing.JButton ButtonThem;
    private javax.swing.JButton ButtonThoat;
    private javax.swing.JButton ButtonTimKiem;
    private javax.swing.JButton ButtonXoa;
    private javax.swing.JComboBox<String> ComboBoxGioiTinh;
    private javax.swing.JLabel LabelLoaiPhong;
    private javax.swing.JLabel LabelMaPhong;
    private javax.swing.JLabel LabelPhongCanTim;
    private javax.swing.JLabel LabelSoSinhVienHienTai;
    private javax.swing.JLabel LabelSoSinhVienToiDa;
    private javax.swing.JLabel LabelTenPhong;
    private javax.swing.JLabel LabelThongTin1;
    private javax.swing.JLabel LabelTinhTrangPhong;
    private javax.swing.JTable TableBangThongTin;
    private javax.swing.JTextField TextFieldMaPhong;
    private javax.swing.JTextField TextFieldPhongCanTim;
    private javax.swing.JTextField TextFieldSoSinhVienHienTai;
    private javax.swing.JTextField TextFieldSoSinhVienToiDa;
    private javax.swing.JTextField TextFieldTenPhong;
    private javax.swing.JTextField TextFieldTinhTrangPhong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
